"""Guards how every job that touches a cell's state binds a GitHub Environment.

Invariants:
- all eight wave jobs, and unlock.yml's `unlock` job, bind the shared-mode
  expression and nothing else: an env listed in vars.SHIPMATE_SHARED_ENVS binds
  the logical name, anything else falls through to <env>-apply. The
  fall-through is the fail-safe direction -- the reviewer gate, the OIDC
  environment claim split and any environment secret all live there -- and
  where that environment does not exist the apply-match fingerprint refuses the
  cell, on every layout that injects a non-empty TF_VAR_* or TF_WORKSPACE
  (CONTRACT.md §Env model states the condition and the one layout that gets no
  refusal);
- snapshot binds no environment at all and complete binds shipmate-engine: a job
  that gains an env-derived binding is the regression;
- snapshot runs the environment pre-flight before it snapshots the apply checks,
  and both before any wave: the pre-flight is only a control while it can still
  refuse the run;
- scripts/verify-environments computes the same binding those jobs bind.

That last one is the price of the pre-flight: the binding rule exists twice, as the YAML ternary
above and as code. Two selectors for one property disagree eventually, so neither side is derived
from the other and the two are never compared to each other. `APPLY_ENV` pins the YAML whole,
`BINDINGS` states the rule's outcome for the cases that distinguish it, and the script is
compared to that.

The realistic failure is accidental regression -- a reverted expression, one missed wave, a new
job that never got the binding, an inverted ternary -- not a hostile edit to these SHA-pinned
files, so one whole-value comparison per job covers it.

Whole parsed values against hand-written constants, never substrings. The YAML folded scalar
(`>-`) collapses the expression's two source lines into one space-joined string, which is why
`APPLY_ENV` is a single line.
"""

import yaml
from _loader import WORKFLOWS, load_script

verify_environments = load_script("verify-environments")

APPLY_ENV = (
    "${{ contains(format(',{0},', vars.SHIPMATE_SHARED_ENVS), "
    "format(',{0},', matrix.environment)) "
    "&& matrix.environment "
    "|| format('{0}-apply', matrix.environment) }}"
)
WAVES = [f"wave{i}" for i in range(8)]

#: workflow file -> the jobs in it that bind an env derived from a cell, written by hand.
#: `unlock` is here, and not only in test_verb_path_isolation.py, because this is one property
#: with one constant: the `<env>-apply` environment is half of what bounds `shipmate unlock`
#: (CONTRACT.md §Comment-ops), and the folded expression is byte-identical to the waves'.
CELL_BOUND = {
    "apply-env-level.yml": WAVES,
    "unlock.yml": ["unlock"],
}

#: (logical env, SHIPMATE_SHARED_ENVS value) -> the environment the apply binds. Hand-written,
#: and the single source for both selectors: never generated from the YAML expression, never
#: generated by running the script.
BINDINGS = {
    ("dev-eu", ""): "dev-eu-apply",  # nothing listed -> split
    ("dev-eu", "dev-eu"): "dev-eu",  # listed -> shared
    ("dev-eu", "prod,dev-eu,stage"): "dev-eu",  # listed among others -> shared
    ("dev-us", "dev-eu, dev-us"): "dev-us-apply",  # the space un-lists the entry
    ("prod", "Prod"): "prod",  # contains() is case-insensitive
    ("dev-us", "dev-us-2"): "dev-us-apply",  # comma boundaries: no prefix match
}

#: snapshot's steps, in order, by action path with the SHA dropped: a repin must not redden
#: this, a reorder must.
SNAPSHOT_STEPS = [
    "ship-iac/shipmate/actions/verify-environments",
    "ship-iac/shipmate/actions/apply-snapshot",
]


def _jobs(workflow="apply-env-level.yml"):
    spec = yaml.safe_load((WORKFLOWS / workflow).read_text(encoding="utf-8"))
    assert isinstance(spec, dict), f"{workflow} did not parse to a mapping"
    return spec["jobs"]


def _wave_jobs():
    jobs = _jobs()
    missing = [w for w in WAVES if w not in jobs]
    assert not missing, f"apply-env-level.yml lost wave jobs: {missing}"
    return {w: jobs[w] for w in WAVES}


def test_every_cell_bound_job_binds_the_shared_or_apply_environment():
    for workflow, job_ids in CELL_BOUND.items():
        jobs = _jobs(workflow)
        missing = [j for j in job_ids if j not in jobs]
        assert not missing, (
            f"{workflow} no longer declares {missing} -- either they were renamed "
            "(update CELL_BOUND) or the cells they bound are now unguarded"
        )
        for job_id in job_ids:
            assert jobs[job_id].get("environment") == APPLY_ENV, (
                f"{workflow} job {job_id!r}: environment must resolve to the logical env "
                "only when it is listed in vars.SHIPMATE_SHARED_ENVS, and to <env>-apply "
                "otherwise -- the apply environment is where the reviewer gate, the OIDC "
                "claim split and the environment secrets live"
            )


def test_snapshot_binds_no_environment_and_complete_binds_the_engine_environment():
    jobs = _jobs()
    # Absence asserted as absence: an explicit `environment:` with a null value is a binding the
    # caller can be made to resolve, and `.get()` would read it as no key at all.
    assert "environment" not in jobs["snapshot"], (
        "snapshot must bind no environment -- it needs no secret, and an "
        "env-derived binding would subject the check snapshot to protection rules"
    )
    assert jobs["complete"].get("environment") == "shipmate-engine"


def test_the_preflight_script_computes_the_binding_the_waves_bind():
    for (env, shared_envs), expected in BINDINGS.items():
        assert verify_environments.apply_binding(env, shared_envs) == expected, (
            f"verify-environments resolved {env!r} against SHIPMATE_SHARED_ENVS="
            f"{shared_envs!r} to something other than {expected!r} -- the pre-flight "
            "would check an environment the waves do not bind"
        )


def test_snapshot_verifies_the_environments_before_snapshotting_the_checks():
    steps = _jobs()["snapshot"]["steps"]
    assert [s["uses"].split("@")[0] for s in steps] == SNAPSHOT_STEPS, (
        "snapshot's steps changed: the environment pre-flight must run first and "
        "the whole job before wave0, or the applies it exists to refuse have "
        "already started"
    )
    assert steps[0].get("continue-on-error") in (None, False), (
        "the pre-flight step is continue-on-error: it would name the missing "
        "environments and let the waves apply into them anyway"
    )
    assert _jobs()["wave0"]["needs"] == ["snapshot"], (
        "wave0 must gate on snapshot, or the pre-flight refuses a run whose first "
        "wave is already applying"
    )
